### ISSUE TITLE
Error when building

### ISSUE THREAD

**Issue by fprl** [opennextjs/opennextjs-cloudflare#42]
Hi, thank you for working on this.

I can't build my app. This is my `wrangler.toml`:
```toml
name = "project"
main = ".worker-next/index.mjs"

compatibility_date = "2024-08-29"
compatibility_flags = ["nodejs_compat_v2"]

assets = { directory = ".worker-next/assets", binding = "ASSETS" }
```

This is what I get after running the command `"build:worker": "cloudflare"` (the project is built and I get to see the summary of the routes in the terminal)
```
○  (Static)   prerendered as static content
ƒ  (Dynamic)  server-rendered on demand

⚙️ Copying files...

# copyPackageTemplateFiles
⚙️ Bundling the worker file...

# patchWranglerDeps
node:fs:448
    return binding.readFileUtf8(path, stringToFlags(options.flag));
                   ^

Error: ENOENT: no such file or directory, open 
'project/apps/web/.worker-next/.next/standalone/apps/web/node_modules/next/dist/compiled/next-server/pages.runtime.prod.js'

Node.js v22.0.0
```

As expected, there is no file under that directory
<img width="312" alt="image" src="https://github.com/user-attachments/assets/42907f39-84b1-424f-8429-99f634e65a38">
